name: Java with Gradle

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Source Checkout
          uses: actions/checkout@v2


        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'


        # jar file build and permission
        - name: Build jar
          run: ./gradlew build bootJAR

